name: test-and-build
on:
  pull_request:
    branches:
      - main

jobs:
  # set working directory to /client to run the unit tests correctly
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: checkout
        uses: actions/checkout@v4

      # set the correct path for package-lock file
      - name: setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: install dependencies
        run: npm ci

      - name: run linting
        run: npm run lint

      - name: run tests
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: unit-tests
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: install dependencies
        run: npm ci

      - name: build
        run: npm run build
